print("Welcome to NDI Application System")
name= input("Fullname: ")
age= input("Age: ")
sex= input( "sex: ")
phone_number=input("phone number: ")
school= input("school: ")
print(f"THANK YOU {name} For applying for NDI APPLICATION SYSTEM, and we have taken note that your name is {name} and that you are {age} years old, and we confirmed that your are a {sex} and you attended {school} we will reach out to you on {phone_number}for further instructions.")
